categories = {
    "Mat og spiselige ting": ['Rema', 'Kiwi', 'coop', 'oda', 'mat', 'food', 'foodora', 'mcd', 'restaurant', 'cafe', 'dining', 'wolt', 'Kebab', 'Pizza', 'Burger', 'Sushi', 'Thai', 'Taco', ''],
    "Entertainment": ['movie', 'cinema', 'concert', 'entertainment'],
    "Reise": ['Vy', 'ruter', 'taxi'],
    "Hobby 3D printing": ['elefun', 'inkclub', '3djake', 'clasohlson'],
    "Hobby: Gaming": ['steam', 'epic', 'game', 'Microsoft', 'playstation', 'xbox', 'gaming', 'nintendo', 'switch', 'blizzard', 'battle.net', 'battle net', 'blizzard entertainment', 'ubisoft', 'ubisoft connect', 'epic games', 'epicgames', 'epic games store', 'epicgamesstore'],
    "Dining": ['restaurant', 'cafe', 'dining', 'food'],
    "Kontooverføringer": ['kontoregulering', 'kontooverføring', 'overføring', 'betalingtpp', "1671"],
    "Sparing": ['morsom', 'avrundet', 'sparing'],
    "Streaming": ['netflix', 'spotify', 'hbo', 'viaplay', 'disney', 'disney+', 'apple tv', 'appletv', 'tv2 play', 'tv2play', 'tidal', 'amazon prime', 'prime video', 'paramount', 'youtube', 'crunchyroll'],
    "Abonnementer": ['abonnement', 'subscription', 'patreon', 'discord', 'twitch', 'Epidemic'],
    "Telefon og mobil": ['telenor', 'ice', 'telia', 'chilimobil', 'talkmore', 'onecall', 'mycall', 'telefonregning', 'mobilregning', 'mobilabonnement', 'mobilepay', 'vipps'],
    "Forsikring og lån": ['if', 'frende', 'tryg', 'gjensidige', 'storebrand', 'dnb', 'sparebank1'],
    "Regninger": ['regning', 'betaling', 'faktura', 'invoice', 'bill', 'payment'],
    "husleie": ['hybel', 'husleie', 'leie', 'utleie', 'utleier', 'utleieforhold', 'utleiekontrakt', 'husleiekontrakt', 'Boliginkasso'],
    "Medisin og helse": ['medisin', 'helse', 'lege', 'apotek', 'sykehus', 'farmasiet', 'helsevesen', 'Vestre Viken', 'sykehusapotek'],
    "Studielån": ['studielån', 'lan', 'utdanning', 'lån', 'lånekassen', 'utdanningslån'],
    "Skole": ['Noroff'],
    "Tech lisenser": ['ai', 'GPT', 'chatgpt', 'openai', 'gptzero'],
    "Bil": ['bil', 'bensin', 'diesel', 'motor', 'vehicle', 'car', 'CirkleK', 'Circle K', 'Shell', 'st1', 'esso', 'bensinstasjon', 'bensinregning', 'dieselregning', 'skruvat', 'biltema', 'biltemabladet'],
    "Billån": ['DNB Finans', 'billån', 'bilregning'],
    "NAV": ['nav', 'arbeidsavklaringspenger', 'AAP'],
    "Vipps": ['vipps', 'vippstransaksjon'],
    "Inkasso": ['inkasso', 'debt collection', 'Collectia'],
    "Lotteri": ['lotteri', 'lotto', 'tipping'],
}
